os: osx
osx_image: xcode13.1
language: objective-c

before_deploy:
- gem install cocoapods
- pod repo add-cdn trunk 'https://cdn.cocoapods.org/'

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    tags: true

script:
  - set -o pipefail && xcodebuild -scheme CampcotCollectionView -workspace CampcotCollectionView.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' build test | xcpretty --color
  - pod lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
